name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-project:
    name: Build Terminal Chess
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7
      - name: Generate CMake build files and run make
        uses: threeal/cmake-action@v2.0.0
      - name: Print out the current directory
        run: pwd
      - name: Print contents of directory
        run: ls -la build
      - name: Run Project
        run: ./build/bin/terminalChess
